defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: burn-vs-all
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

voted_logit: ${connected_dir}/logits/${voted_name}.npy
submission_file: ${connected_dir}/metadata/test.csv
target_column_name: label
voted_file: ${connected_dir}/submissions/${voted_name}.csv

votings:
  logit1: 0.25
  logit2: 0.25
  logit3: 0.25
  logit4: 0.25